services:
  backend:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./shared:/shared
    restart: on-failure

    command: "npm run dev_sepolia"
  
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    #! command:  SPECIFIC TO OTHER compose files 
    volumes:
      - ./shared:/shared