services:
  # backend:
    # build: ./server
    # ports:
    #   -"3001:3001"
    # volumes:
    #   - ./shared:/shared
    # restart: on-failure
    # env_file:
    # command: "npm run dev_sepolia"
  
  client:
    build: ./client
    ports:
      - "3000:3000"
    # depends_on:
    #   - backend
    command: sh -c "npm run build_docker && npm run start_docker"
    volumes:
      - ./shared:/shared