import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
// import Providers from "./providers";
import AccountContextProvider from "./context/AccountContext";


const inter = Inter({ subsets: ["latin"], variable: "--font-inter", });

export const metadata: Metadata = { title: "Create Next App", description: "Generated by create next app",};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  return (
      <html lang="en" className={inter.variable}>
      <body className={'antialiased'}>
        {/* <Providers>
          <Navbar></Navbar>
          {children}
        </Providers> */}

        <AccountContextProvider>
          <Navbar></Navbar>
          {children}
        </AccountContextProvider>

      </body>
    </html>
  )
}
